language: java
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    - maksimilian.koturanov@gmail.com

install: ignore

script: mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
